name: Update Language Statistics

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-stats:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: StefVuck/Github-Language-Stats@v1.1.0
        continue-on-error: true
        with:
          github_token: ${{ secrets.STATS_TOKEN }}
          visualization_types: "leaderboard"
          output_path: "stats"
          dark_mode: true
          exclude_languages: "HTML,CSS,NIX,Ruby,SCSS"
          include_forks: true
      - name: Add and Commit badge_cache
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add stats/.badge_cache/ || true
          git commit -m "Update badge cache" || echo "Nothing to commit"
          git push || echo "Nothing to push"
          
